export const GET_CHOSEN_CONTACTS_REQUEST = "GET_CHOSEN_CONTACTS_REQUEST";
export const GET_CHOSEN_CONTACTS_SUCCESS = "GET_CHOSEN_CONTACTS_SUCCESS";
export const GET_CHOSEN_CONTACTS_FAIL = "GET_CHOSEN_CONTACTS_FAIL";
