export const GET_CHOSEN_ROOMS_REQUEST = "GET_CHOSEN_ROOMS_REQUEST";
export const GET_CHOSEN_ROOMS_SUCCESS = "GET_CHOSEN_ROOMS_SUCCESS";
export const GET_CHOSEN_ROOMS_FAIL = "GET_CHOSEN_ROOMS_FAIL";

export const INCREMENT_ROOM_LIKE_REQUEST = "INCREMENT_ROOM_LIKE_REQUEST";
export const INCREMENT_ROOM_LIKE_SUCCESS = "INCREMENT_ROOM_LIKE_SUCCESS";
export const INCREMENT_ROOM_LIKE_FAIL = "INCREMENT_ROOM_LIKE_FAIL";
